### ISSUE TITLE
Supprimer la signature framasoft

### ISSUE THREAD

**Issue by tomdereub** [YunoHost-Apps/opensondage_ynh#19]
Quand opensondage envoie des mails, il y a une signature en bas : 
« La route est longue, mais la voie est libre… »
Framasoft ne vit que par vos dons (déductibles des impôts).
Merci d’avance pour votre soutien http://soutenir.framasoft.org.

Même si je reconnais leur travail pour le développement de cette application, je ne veux pas de cette signature sur une application qui tourne sur mon serveur, d'autant que ça rend le débat "décentralisation du net" encore plus confus...

C'est possible de la retirer du code ?

**Comment by frju365** [comment]
Fixé normalement dans la pr #20

**Comment by tomdereub** [comment]
La signature framasoft est revenue après la dernière upgrade.
