### ISSUE TITLE
Instal not working

### ISSUE THREAD

**Issue by augustindo** [YunoHost-Apps/opensondage_ynh#21]
Hi,
First of all thanks for this nice package !
For a while I've some trouble trying to install this package in yunohost.
If I run a `yunohost app install opensondage` I got
```
Warning: Wrong admin
Warning: ERROR 1008 (HY000) at line 1: Can't drop database 'opensondage'; database doesn't exist
Warning: ERROR 1396 (HY000) at line 1: Operation DROP USER failed for 'opensondage'@'localhost'
Success! The SSOwat configuration has been generated
Error: Installation failed
```
I've tried with 3 differents existing users.
I'm not sure but I think that I installed and removed this app in the past.

For info my yunohost server is running on a VPS hosted by Gandi.
```
yunohost: 2.7.2
yunohost-admin: 2.7.2
moulinette: 2.7.2
ssowat: 2.7.2
```
Thanks in advance !

**Comment by frju365** [comment]
Can you retry to install OpenSondage ?

**Comment by zamentur** [comment]
I think we can close, someone in ARN confirm it works well now (and CI test result  is 7).
