### ISSUE TITLE
Update breaks Nginx configuration

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/opensondage_ynh#24]
I updated the app manually with `sudo yunohost app upgrade opensondage -u https://github.com/YunoHost-Apps/opensondage_ynh --verbose `

The nginx reload at the end of the script failed, for the following reason : the configuration file is badly re-written, as the first line misses an initial "/" in the location call :
```
location  {
       alias /var/www/opensondage/;
       if ($scheme = http) {
            rewrite ^ https://$server_name$request_uri? permanent;
       }
...
```

I was able to identify this and fix it, but I am not skilled enough to propose a fix to the package. However I'm available to provide more data if needed.

Thanks in advance for the fix !

**Comment by maniackcrudelis** [comment]
This problem should be fixed by the current testing https://github.com/YunoHost-Apps/opensondage_ynh/pull/23.
It should be fix soon in the master branch.

Thanks anyway to have reported this bug.

**Comment by frju365** [comment]
Ok. Fixed !
