### ISSUE TITLE
Polls lost after uprade

### ISSUE THREAD

**Issue by tomdereub** [YunoHost-Apps/opensondage_ynh#27]
I've lost all existing polls after upgrading last week.

**Comment by SiM** [comment]
Do you mean that your 'poll' table in mysql is empty ? Or that the poll's urls you had doesn't work anymore ?
On the second case (I experienced the same issue), create a new poll, check the url scheme and compare it to your previous urls.
In my case I had to replace "sondage=" with "poll=".
You can also try to use the "Where are my polls?" functionality.

**Comment by tomdereub** [comment]
Ok you're right, if I replace "sondage" with "poll" it works... But the "where ar my polls?" functionality didn't work, the result with my email adress is empty.
Thanks !

**Comment by tomdereub** [comment]
I've finally removed and reinstalled the app and it works (but this time I really lost existing polls).

**Comment by Jibec** [comment]
good, so I did not destroy everything, but for some reason, the URL changed... I'll try to have a look this weekend...

**Comment by SiM** [comment]
> But the "where ar my polls?" functionality didn't work, the result with my email adress is empty (blank page).
> And I can't create new polls, the page "create_date_poll.php" is blank at the end of the process. I'll try a reboot tonight.

These problems should be related to #31

**Comment by Jibec** [comment]
I had a look, but the name change is something I don't understand yet..
