### ISSUE TITLE
Gestion des droits d'accès

### ISSUE THREAD

**Issue by tomdereub** [YunoHost-Apps/opensondage_ynh#28]
J'ai un problème avec la gestion des droits d'accès : je voudrais que tous mes utilisateurs voient l'application sur le SSO Yunohost. Sauf que si on donne l'accès dans l'interface admin de yunohost, ça donne aussi accès à l'admin de Opensondage, ce que je ne veux pas...
Est-ce qu'il y aurait un moyen de dissocier l'accès admin de l'apparition de la "tuile" opensondage ?

**Comment by zamentur** [comment]
Pas encore mais le travail de Josue permettra bientôt ça

**Comment by plslvval** [comment]
cette fonctionalité n'est pas disponible au 4 avril 2020, est-ce dans les tuyaux ?

**Comment by yalh76** [comment]
les droits d'accés sont maintenant gérés dans YunoHost
