### ISSUE TITLE
option à l'installation peu parlante

### ISSUE THREAD

**Issue by vivienkit** [YunoHost-Apps/opensondage_ynh#37]
L'option "case à cocher" à l'installation qui propose d'autoriser les utilisateurs non-authentifiés à **créer** des sondages n'est pas assez parlante à mon avis. En effet, si on décoche cette option, les utilisateurs non-authentifiés ne peuvent pas non plus **répondre** à un sondage.

**Comment by Jibec** [comment]
c'est tout à fait vrai, mais c'est un doublog de #36

**Comment by vivienkit** [comment]
oups désolé, je clôture le doublon du coup...
