### ISSUE TITLE
Non-loged in users can't use 'author' link

### ISSUE THREAD

**Issue by spctrlth** [YunoHost-Apps/opensondage_ynh#48]
**Steps to reproduce:**
1. Install the app allowing non-logged in users to create polls
2. Create a poll while not being logged in
3. At the end you will be redirected to the link you get to change your poll (the same link you get in your mailbox as author)

**Expected behaviour:**
I see the page to make changes to my poll

**Current behaviour:**
You are redirected to the loginscreen

**Extra:**
The same problem occurs when you follow the link directly
I assume this is fixable in the nginx config somewhere
The url you're directed to is from the form https://parley.be/poll/adminstuds.php?poll=<some_id>

**Comment by kay0u** [comment]
Hello, thank you for this issue.

A PR will soon be merged to solve this problem: #47

**Comment by kay0u** [comment]
Closed by #51
