### ISSUE TITLE
Any easy way to customize it?

### ISSUE THREAD

**Issue by tiotrom** [YunoHost-Apps/opensondage_ynh#68]
I apologize if this is not the place to ask/discuss this, and feel free to close it if so, but I am wondering how can one properly customize this ynh app. I am talking about theming it. Cheers!

**Comment by yalh76** [comment]
You should look at the upstream app: https://framagit.org/framasoft/framadate/framadate

**Comment by tio-trom** [comment]
Yup thanks!
