### ISSUE TITLE
OpenSondage - Installation failed with Domain Name including "-"

### ISSUE THREAD

**Issue by Papillone** [YunoHost-Apps/opensondage_ynh#78]
The installation of OpenSondage failed:
[Error Log](https://paste.yunohost.org/ozadaqutok)

The error message says: Domäne 'kn.cloud.de' unbekannt
But my Domain is kn-cloud.de

Yunohost Version:  4.2.8.1 (stable)

**Comment by SiM** [comment]
Hi,
This issue was already reported here: https://github.com/YunoHost-Apps/opensondage_ynh/issues/67
